version: '3'

services:
  web:
    container_name: competition-model-app
    env_file:
      - .env
    build:
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src